# Generated by Django 4.2.3 on 2023-07-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogHeader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alt", models.CharField(max_length=255)),
                ("image_path", models.CharField(max_length=255)),
                ("has_correct_dimension", models.BooleanField(default=False)),
            ],
        ),
    ]
